### ISSUE TITLE
Remove Cruft

### ISSUE THREAD

**Issue by de-sh** [mec-dev/MEC.conf#1]
There are a lot of unnecessary items within the website, be it JS tools or animations. Remove and replace the same if required with better solutions.

*NOTE:* Please point out unnecessary js files and mention them for discussion before removal so that everyone is on the same page.

**Comment by iambk** [comment]
Do you want the effect/animation of the text sliding in during the scroll? If not, we can remove some of the CSS and font files.
Regarding js files, the site seems to break completely even if a single js file is excluded (I'm clueless why). So the least we can do is maybe include CDN links to improve performance (that again is debatable).

**Comment by de-sh** [comment]
> Do you want the effect/animation of the text sliding in during the scroll? If not, we can remove some of the CSS and font files.

No, it looks good, let it be... but try your best to remove as many of the JS files as possible

**Comment by de-sh** [comment]
Seems like we can close this
