### ISSUE TITLE
Over lapping text in COC

### ISSUE THREAD

**Issue by kurianbenoy** [mec-dev/MEC.conf#12]
![Screenshot-2019-5-21 MEC conf 2019](https://user-images.githubusercontent.com/24592806/58117342-f7828c80-7c1b-11e9-93eb-fe42ab216c40.png)

**Comment by de-sh** [comment]
The whole COC concept seems broken, maybe we should remove it completely?

What do you think @annu12340?

**Comment by annu12340** [comment]
Made the required change

![image](https://user-images.githubusercontent.com/43414928/58196257-8ad4c400-7ce7-11e9-8322-458cea9258b2.png)

**Comment by de-sh** [comment]
COC-boxes are becoming an issue, even with the latest updates, things are not working. I guess it will be better to just remove it all together.

@annu12340 can you work on something else, maybe related to the home section?
@kurianbenoy close?

**Comment by annu12340** [comment]
okay
