### ISSUE TITLE
Create a Registration Modal(popup modal to the registration portal for buying tickets.)

### ISSUE THREAD

**Issue by de-sh** [mec-dev/MEC.conf#19]
A modal to guide registrants to get access to the registration portal will help visitors register tickets for the event from the service that we choose to utilise for this purpose.

**Comment by kurianbenoy** [comment]
By modal what do you mean? A screencast on how to register tickets for events?

**Comment by de-sh** [comment]
We need a popup modal containing the iframe on the delegate page which will take you to the registration portal for buying tickets.

**Comment by de-sh** [comment]
Would really appreciate if you could mention the work done and mark issues as solved @akhilseshan :sweat_smile: 

BTW, it seems like the portal is not loading. Can you by any chance provide a direct link to it?

**Edit:** Seems like the registrations turned off
