### ISSUE TITLE
Create Conf carousel in main

### ISSUE THREAD

**Issue by de-sh** [mec-dev/MEC.conf#23]
The current website has a stationary image as the background, it will be better if it were a dynamic carousel that had all the images in a sequence.

**Comment by annu12340** [comment]
okay

**Comment by de-sh** [comment]
Good work @annu12340.

CC: @akhilseshan @kurianbenoy 

Please refer conversation in #25 and please make PRs into `mec-dev:bg-carousel` to change images as required, within the carousel. We can make final PR to close this after sufficiently good images are loaded here.

**Comment by de-sh** [comment]
Please take a look at the carousel as implemented currently. Do give some suggestions... Really require it at the moment
