### ISSUE TITLE
Make home section responsive.

### ISSUE THREAD

**Issue by iambk** [mec-dev/MEC.conf#3]
Currently, only the home section of the webpage is not responsive for smaller screen sizes (to be precise, for screen width less than 625px).
Figure out what all CSS styles home section uses and fix it to make it responsive for all screen sizes.

**Comment by de-sh** [comment]
I would love it if you removed it completely... Doesn't seem to fit the purpose it was made out for. We can instead do something similar to what fossmeet.in did
