### ISSUE TITLE
Creating a Ticket section to show different options of tickets

### ISSUE THREAD

**Issue by de-sh** [mec-dev/MEC.conf#31]
We have three tickets for registrants to select:

| Student | Professional | Team(Both Student and Professional) |
| -----------|:-----------------:| --------------------------------------------------:|
|  ₹1000  |  ₹1500          |   15% OFF                                           |

All contain the following: Pass, Swags, T-Shirt and some more.
Use what ieee.sjcetpalai.ac.in at the bottom. 

Within the registration section

**Comment by kurianbenoy** [comment]
Needs to be heavily modified at the moment. Make a consensus in group at first
