### ISSUE TITLE
Create DevSprint Page

### ISSUE THREAD

**Issue by de-sh** [mec-dev/MEC.conf#32]
Currently the DevSprint page conf.mec.dev/sprint is a form to be filled by interested communities. Once the form is closed and registration starts, details about the projects to be worked on needed to be added over here.

**Comment by kurianbenoy** [comment]
- Add details of confirmed organisations  with logos

**Comment by de-sh** [comment]
Also make sure the QA is shown as a FAQ format as done in https://codyhouse.co/gem/css-faq-template/
