### ISSUE TITLE
Improve web page performance

### ISSUE THREAD

**Issue by kurianbenoy** [mec-dev/MEC.conf#33]
- Current webpage take lot of time to load

**Possible fixes**
1. Remove multiple images in slider in home page
2. Remove MEC.dev loader
3. Make speakers in a seperate page

**Comment by agzuniverse** [comment]
I think we should have all the information regarding devsprints/speakers/workshops in the homepage. It's significantly more likely to capture attention than hiding them behind links. Other areas you mentioned definitely need optimization, the total data loaded is in excess of 2.44mb (!)

**Comment by kurianbenoy** [comment]
I agree, before any change @agzuniverse  please make it as a PR

**Comment by de-sh** [comment]
> the total data loaded is in excess of 2.44mb (!)

is there any way we could async load the images and level up the speeds to just being the html+css at start?

**Comment by agzuniverse** [comment]
If we async loaded all the images the webpage would be weirdly empty till it loads.

The images can use a lot of compression. I'll see if I can do it.
