### ISSUE TITLE
Add software and hardware track info

### ISSUE THREAD

**Issue by kurianbenoy** [mec-dev/MEC.conf#34]
One of the main highlights of our conference is the opportunity of having two tracks:

- Software track
- Hardware track

Create a somewhat similar page in the home page itself with information
![Screenshot-2019-6-29 FOSSASIA Summit 2019](https://user-images.githubusercontent.com/24592806/60384740-4fc07000-9a9f-11e9-980a-3e29fcf97080.png)

**Comment by de-sh** [comment]
Lets converse before we do this!!!

We are randomly doing different stuff, better not push directly, so please make PRs

@kurianbenoy @agzuniverse
